# Generated by Django 4.1.7 on 2023-03-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coassets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
