# Generated by Django 4.1.7 on 2023-03-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coassets', '0003_device_log_alter_device_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
