# Generated by Django 4.1.7 on 2023-03-12 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coassets', '0004_device_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='employee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='coassets.employee'),
        ),
    ]
